[project]
name = "cognite_dm_skilling"
version = "0.1.0"
description = "Toolkit project for data modelling upskiling workshop"
authors = [{ name = "Maciej Marciniak", email = "maciej.marciniak@cognite.com" }]
requires-python = ">=3.11,<3.14"
dependencies = [
    # Cognite ecosystem
    "cognite-sdk",
    "cognite-toolkit==0.6.87",
    "cognite-pygen",

    # Data Engineering essentials
    "pandas",
    "numpy",
    "openpyxl",
    "orjson",

    # Developer tools
    "python-dotenv",
    "pydantic",
    "pydantic-settings",
    "typer",
    "arrow",
    "requests",
    "httpx",

    # Visualization & App building
    "matplotlib",
    "seaborn",
    "plotly",

    # Streamlit
    "streamlit",

    # Retry / Resilience
    "tenacity",

    # ML / AI Essentials
    "scikit-learn",
    "xgboost",
    "tqdm",
    "joblib",

    # Optional cache handling (useful for APIs)
    "cachetools",
    "fastapi>=0.116.1,<0.117",
    "uvicorn>=0.35.0,<0.36",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "pytest",
    "pytest-cov",
    "faker",
    "mypy",
    "notebook",
    "ipykernel",
    "types-requests",
    "types-python-dateutil",
    "types-pyyaml",
    "nbstripout>=0.9.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "ANN", "UP", "S"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]  # Allow 'assert' in tests
